
export const QUIZ_SUCCESS= "QUIZ_SUCCESS";
export const QUIZ_REQUEST= "QUIZ_REQUEST";
export const QUIZ_FAILURE= "QUIZ_FAILURE";

export const QUIZ_POST_SUCCESS= "QUIZ_POST_SUCCESS";
export const QUIZ_POST_REQUEST= "QUIZ_POST_REQUEST";
export const QUIZ_POST_FAILURE= "QUIZ_POST_FAILURE";



export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
